
#include "driver.h"

#ifdef ALLOC_PRAGMA
#pragma alloc_text (PAGE, PlanckDeviceCreate)
#pragma alloc_text (PAGE, PlanckEvtDeviceSelfManagedIoSuspend)
#endif

NTSTATUS
PlanckDeviceCreate(
    PWDFDEVICE_INIT DeviceInit
    )

{
    WDF_OBJECT_ATTRIBUTES   deviceAttributes;
    PDEVICE_CONTEXT deviceContext;
    WDF_PNPPOWER_EVENT_CALLBACKS    pnpPowerCallbacks;
    WDFDEVICE device;
    NTSTATUS status;

    PAGED_CODE();

    WDF_PNPPOWER_EVENT_CALLBACKS_INIT(&pnpPowerCallbacks);

    //
    // Register pnp/power callbacks so that we can start and stop the timer as the device
    // gets started and stopped.
    //
    pnpPowerCallbacks.EvtDeviceSelfManagedIoInit    = PlanckEvtDeviceSelfManagedIoStart;
    pnpPowerCallbacks.EvtDeviceSelfManagedIoSuspend = PlanckEvtDeviceSelfManagedIoSuspend;

    #pragma prefast(suppress: __WARNING_CLASS_MISMATCH, "Function used for both Init and Restart Callbacks")
    pnpPowerCallbacks.EvtDeviceSelfManagedIoRestart = PlanckEvtDeviceSelfManagedIoStart;

    //
    // Register the PnP and power callbacks. Power policy related callbacks will be registered
    // later in SotwareInit.
    //
    WdfDeviceInitSetPnpPowerEventCallbacks(DeviceInit, &pnpPowerCallbacks);

    WDF_OBJECT_ATTRIBUTES_INIT_CONTEXT_TYPE(&deviceAttributes, DEVICE_CONTEXT);

    status = WdfDeviceCreate(&DeviceInit, &deviceAttributes, &device);

    if (NT_SUCCESS(status)) {
        //
        // Get the device context and initialize it. WdfObjectGet_DEVICE_CONTEXT is an
        // inline function generated by WDF_DECLARE_CONTEXT_TYPE macro in the
        // device.h header file. This function will do the type checking and return
        // the device context. If you pass a wrong object  handle
        // it will return NULL and assert if run under framework verifier mode.
        //
        deviceContext = WdfObjectGet_DEVICE_CONTEXT(device);
        deviceContext->PrivateDeviceData = 0;

        //
        // Create a device interface so that application can find and talk
        // to us.
        //
        status = WdfDeviceCreateDeviceInterface(
            device,
            &GUID_DEVINTERFACE_PLANCK,
            NULL // ReferenceString
            );

        if (NT_SUCCESS(status)) {
            //
            // Initialize the I/O Package and any Queues
            //
            //status = PlanckQueueInitialize(device);
        }
    }

    return status;
}


NTSTATUS
PlanckEvtDeviceSelfManagedIoStart(
    IN  WDFDEVICE Device
    )
{
    KdPrint(("--> PlanckEvtDeviceSelfManagedIoInit\n"));

    KdPrint(( "<-- PlanckEvtDeviceSelfManagedIoInit\n"));

    return STATUS_SUCCESS;
}

NTSTATUS
PlanckEvtDeviceSelfManagedIoSuspend(
    IN  WDFDEVICE Device
    )

{
    PAGED_CODE();

    KdPrint(("--> PlanckEvtDeviceSelfManagedIoSuspend\n"));

    KdPrint(( "<-- PlanckEvtDeviceSelfManagedIoSuspend\n"));

    return STATUS_SUCCESS;
}



